package client

import (
	"fmt"
	"os"

	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/rest"
	"k8s.io/client-go/tools/clientcmd"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

// Client 封装 Kubernetes 客户端
type Client struct {
	// Client is the controller-runtime client
	client client.Client

	// Clientset is the official Kubernetes clientset
	clientset *kubernetes.Clientset

	// Config is the REST config
	config *rest.Config
}

// New creates a new HCS client
func New() (*Client, error) {
	cfg, err := rest.InClusterConfig()
	if err != nil {
		// Fall back to kubeconfig
		kubeconfig := os.Getenv("KUBECONFIG")
		if kubeconfig == "" {
			kubeconfig = clientcmd.RecommendedHomeFile
		}
		cfg, err = clientcmd.BuildConfigFromFlags("", kubeconfig)
		if err != nil {
			return nil, fmt.Errorf("failed to create kubeconfig: %w", err)
		}
	}

	k8sClient, err := client.New(cfg, client.Options{})
	if err != nil {
		return nil, fmt.Errorf("failed to create k8s client: %w", err)
	}

	clientset, err := kubernetes.NewForConfig(cfg)
	if err != nil {
		return nil, fmt.Errorf("failed to create clientset: %w", err)
	}

	return &Client{
		client:    k8sClient,
		clientset: clientset,
		config:    cfg,
	}, nil
}

// GetClient returns the controller-runtime client
func (c *Client) GetClient() client.Client {
	return c.client
}

// GetClientset returns the Kubernetes clientset
func (c *Client) GetClientset() *kubernetes.Clientset {
	return c.clientset
}

// GetConfig returns the REST config
func (c *Client) GetConfig() *rest.Config {
	return c.config
}

// TODO: Add ComputeNode CRUD operations after running controller-runtime codegen
// The ComputeNode types need DeepCopyObject methods generated by:
// go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.16.0
// controller-gen object:headerFile="doc.go" paths="./..."
